[package]
name = "renderingbasics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17" # make sure this is the latest version

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
